clean::
	$(HIDE)rm .lia.cache 2> /dev/null || true
	$(HIDE)rm .nia.cache 2> /dev/null || true
	$(HIDE)rm */.*.aux 2> /dev/null || true
	$(HIDE)rm */*.glob 2> /dev/null || true
	$(HIDE)rm */*.v.d 2> /dev/null || true
	$(HIDE)rm *.dpd 2> /dev/null || true

DPD = $(wildcard *.dpd)
DOT = $(DPD:%.dpd=%.dot)
PNG = $(DPD:%.dpd=%.png)
PDF = $(DPD:%.dpd=%.pdf)

%.dot: %.dpd
	dpd2dot $<

%.png: %.dot
	dot -Tpng $< -o $@

%.pdf: %.dot
	dot -Tpdf $< -o $@

graph: $(PNG)
pdf: $(PDF)
